name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    # Manually pull/start image/container due to its permission/USER.
    - name: Pull Falaise Docker Image
      run: docker pull supernemo/falaise-centos7-base:develop
    - name: Create Docker Container
      run: docker run -itd --name builder -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE supernemo/falaise-centos7-base:develop 
    - name: Install Falaise@HEAD
      run: docker exec builder bash -c "brew install falaise --HEAD --cc=gcc-7"   
    # Now the actual build...
    - uses: actions/checkout@v2
    - name: Check our environment
      run: |
        docker exec builder bash -c "ls -larth $GITHUB_WORKSPACE"
        docker exec builder bash -c "mkdir build"
        docker exec builder bash -c "cd build && CC=gcc-7 CXX=g++-7 cmake $GITHUB_WORKSPACE && make"
        
        
