name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  falaise-centos7:
    runs-on: ubuntu-latest
    container:
      image: supernemo/falaise:latest
      env:
        HOME: /home/snemo
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test where we are
        run: |
          env
          ls -larth /
          which brew
