name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  falaise-centos7:
    runs-on: ubuntu-latest
    container:
      image: supernemo/falaise:latest
      options: --user 1001
    steps:
      - name: Test how we are running
        run: |
          env
          ls -larth /
          which brew
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Falaise@develop
        run: |
          brew unlink falaise
          brew install falaise --HEAD --cc=gcc-7
      
